from __future__ import annotations

"""
tile_generator.py — orchestrate GRIB2 → RGBA → PNG tiles for one (map_type, run_id, fff).

GRIB2 path convention (noaa_be internal):
  data/<map_type>/<run_id>/<product_name>/f<fff:03d>.grib2
  e.g. data/rain_basic/20260406_00z/apcp_surface/f000.grib2

Strategy:
  - Eager: z=0..TILE_ZOOM_EAGER_MAX saved to staging dir then atomic-swapped to live
    - Lazy:  z=TILE_ZOOM_EAGER_MAX+1..TILE_ZOOM_LAZY_MAX generated on demand and cached
  - cloud_layered: three products (low_cloud, mid_cloud, high_cloud) per frame
"""

import logging
import shutil
import time
from pathlib import Path

import numpy as np

from ..config import get_settings
from ..core.grib_reader import GribField, read_first_field, read_multi_fields
from ..core.map_specs import MAP_SPECS
from ..core.tile_cutter import cut_and_save, get_lazy_tile

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Map-type → tile product mapping
# (product name == MAP_SPECS Product.name == sub-folder under run_id/)
# ---------------------------------------------------------------------------

# Products we generate PNG tiles for (wind_animation is JSON-only)
# Each entry maps:  map_type → [product_name, ...]
# product_name also doubles as the GRIB file sub-folder name.
_MAP_PRODUCTS: dict[str, list[str]] = {
    "temperature_feels_like": ["tmp_2m"],
    "rain_basic":             ["apcp_surface"],
    # generated by precip_pipeline
    "rain_advanced":          ["precip_base", "precip_fx"],
    "cloud_total":            ["tcdc_entire_atmosphere"],
    "cloud_layered":          ["low_cloud", "mid_cloud", "high_cloud"],
    "snow_depth":             ["snod_surface"],
    "wind_surface":           ["wind_base", "wind_field"],
}

# GRIB short names expected inside each product's GRIB2 file
_PRODUCT_SHORT_NAMES: dict[str, list[str]] = {
    "tmp_2m":                 ["2t", "t2m", "t"],
    "apcp_surface":           ["tp", "apcp"],
    "rain_adv_surface":       ["prate", "crain", "csnow", "cicep", "cfrzr", "cpofp"],
    "tcdc_entire_atmosphere": ["tcc", "tcdc"],
    "low_cloud":              ["lcc", "lcdc"],
    "mid_cloud":              ["mcc", "mcdc"],
    "high_cloud":             ["hcc", "hcdc"],
    "snod_surface":           ["sde", "snod"],
}

# colormap product key → one of _PRODUCT_SHORT_NAMES
# (the first short_name found in the file is used for RGBA)
_COLORMAP_PRODUCT: dict[str, str] = {
    "tmp_2m":                 "temperature_feels_like",
    "apcp_surface":           "rain_basic",
    "rain_adv_surface":       "rain_advanced",
    "tcdc_entire_atmosphere": "cloud_total",
    "low_cloud":              "cloud_layered",
    "mid_cloud":              "cloud_layered",
    "high_cloud":             "cloud_layered",
    "snod_surface":           "snow_depth",
}

_COLORMAP_PRODUCT_ARG: dict[str, str | None] = {
    "tmp_2m":                 None,
    "apcp_surface":           None,
    "rain_adv_surface":       None,
    "tcdc_entire_atmosphere": None,
    "low_cloud":              "low_cloud",
    "mid_cloud":              "mid_cloud",
    "high_cloud":             "high_cloud",
    "snod_surface":           None,
}


# Extra filter keys needed for products whose GRIB file has multiple stepTypes
_PRODUCT_EXTRA_FILTERS: dict[str, dict] = {
    "rain_adv_surface": {"stepType": "instant"},
}


# ---------------------------------------------------------------------------
# GRIB loading helpers
# ---------------------------------------------------------------------------

def _load_primary_field(file_path: Path, product_name: str) -> GribField:
    """Load the first available GRIB short name for this product."""
    candidates = _PRODUCT_SHORT_NAMES.get(product_name, [])
    extra = _PRODUCT_EXTRA_FILTERS.get(product_name, {})
    last_exc: Exception | None = None
    for sn in candidates:
        try:
            return read_first_field(file_path, filter_by_keys={"shortName": sn, **extra})
        except Exception as exc:
            last_exc = exc
    # fallback: open without filter
    try:
        return read_first_field(file_path)
    except Exception:
        raise ValueError(
            f"Cannot read GRIB field from {file_path.name} for product={product_name!r}"
        ) from last_exc


# ---------------------------------------------------------------------------
# Single-frame tile generation
# ---------------------------------------------------------------------------

def generate_frame(
    map_type: str,
    run_id: str,
    fff: int,
    product_name: str,
    data_dir: Path,
    output_dir: Path,
    zoom_min: int = 0,
    zoom_max: int | None = None,
    workers: int | None = None,
    skip_existing: bool = True,
) -> dict:
    """
    Generate PNG tiles for one (map_type, run_id, fff, product_name) frame.

    GRIB2 read from: data_dir/<map_type>/<run_id>/<product_name>/f<fff:03d>.grib2
    Tiles saved to:  output_dir/<map_type>/<run_id>/f<fff:03d>/<product_name>/{z}/{x}/{y}.png

    Special case: cloud_total is handled by cloud_pipeline.generate_cloud_frame
    which auto-detects TCDC total field vs layered (LCDC/MCDC/HCDC) fallback.
    """
    # cloud_total delegates to smart cloud pipeline (total → layered fallback)
    if map_type == "cloud_total":
        from ..core.cloud_pipeline import generate_cloud_frame
        return generate_cloud_frame(
            run_id=run_id,
            fff=fff,
            data_dir=data_dir,
            output_dir=output_dir,
            zoom_min=zoom_min,
            zoom_max=zoom_max,
            workers=workers,
            skip_existing=skip_existing,
        )

    # rain_advanced delegates to precip_pipeline (base tile + fx mask tile)
    if map_type == "rain_advanced":
        from ..core.precip_pipeline import generate_precip_frame
        return generate_precip_frame(
            run_id=run_id,
            fff=fff,
            data_dir=data_dir,
            output_dir=output_dir,
            zoom_min=zoom_min,
            zoom_max=zoom_max,
            workers=workers,
            skip_existing=skip_existing,
        )

    # wind_surface delegates to wind_pipeline
    if map_type == "wind_surface":
        from ..core.wind_pipeline import generate_wind_frame
        return generate_wind_frame(
            run_id=run_id,
            fff=fff,
            data_dir=data_dir,
            output_dir=output_dir,
            zoom_min=zoom_min,
            zoom_max=zoom_max,
            workers=workers,
            skip_existing=skip_existing,
        )

    cfg = get_settings()
    z_max = zoom_max if zoom_max is not None else cfg.TILE_ZOOM_EAGER_MAX
    w = workers if workers is not None else cfg.TILE_WORKERS

    grib_file = data_dir / map_type / run_id / \
        product_name / f"f{fff:03d}.grib2"
    if not grib_file.exists():
        return {"skipped": True, "reason": f"GRIB missing: {grib_file}"}
    if grib_file.stat().st_size == 0:
        log.debug("Skipping empty GRIB file: %s", grib_file)
        return {"skipped": True, "reason": f"GRIB empty (0 bytes): {grib_file.name}"}

    field = _load_primary_field(grib_file, product_name)
    cmap_type = _COLORMAP_PRODUCT.get(product_name, map_type)
    cmap_product = _COLORMAP_PRODUCT_ARG.get(product_name)

    start_ts = time.perf_counter()
    summary = cut_and_save(
        scalar=field.values,
        lat=field.lat,
        lon=field.lon,
        cmap_type=cmap_type,
        cmap_product=cmap_product,
        run_id=run_id,
        fff=fff,
        product=product_name,
        output_dir=output_dir,
        zoom_min=zoom_min,
        zoom_max=z_max,
        workers=w,
        skip_existing=skip_existing,
    )
    elapsed = time.perf_counter() - start_ts
    # attach timing info
    summary["duration_s"] = round(elapsed, 3)

    log.info(
        "Tiles %s/%s/f%03d/%s: saved=%d skipped=%d errors=%d duration=%.3fs",
        map_type, run_id, fff, product_name,
        summary.get("saved", 0), summary.get(
            "skipped", 0), summary.get("errors", 0),
        summary["duration_s"],
    )
    return summary


# ---------------------------------------------------------------------------
# Full-run tile generation (staging → atomic swap)
# ---------------------------------------------------------------------------

def generate_run(
    map_type: str,
    run_id: str,
    fff_values: list[int],
    data_dir: Path | None = None,
) -> dict:
    """
    Generate tiles using the new Multi-Tier Pipeline Orchestrator.
    Submits jobs to the async queues and blocks until completed (to preserve existing API).
    """
    cfg = get_settings()
    d_dir = data_dir or cfg.DATA_DIR

    if map_type in cfg.JSON_ONLY_MAP_TYPES:
        return {"skipped_json_only": True, "map_type": map_type, "run_id": run_id}

    products = _MAP_PRODUCTS.get(map_type, [])
    staging = cfg.STAGING_DIR / map_type / run_id
    live = cfg.TILES_DIR / map_type / run_id
    staging.mkdir(parents=True, exist_ok=True)

    # Progress tracking (import lazily so tile_generator works standalone too)
    try:
        from . import progress_tracker as _pt
    except ImportError:
        _pt = None  # type: ignore

    # --- Count ACTUAL GRIB2 files on disk (not just the requested list) ---
    actual_fff_set: set[int] = set()
    run_data_dir = d_dir / map_type / run_id
    if run_data_dir.exists():
        for prod_dir in run_data_dir.iterdir():
            if prod_dir.is_dir():
                for gf in prod_dir.glob("f*.grib2"):
                    try:
                        actual_fff_set.add(int(gf.stem[1:]))
                    except ValueError:
                        pass

    # Only generate frames that are both requested AND on disk
    effective_fffs = sorted(f for f in fff_values if f in actual_fff_set) if actual_fff_set else sorted(fff_values)

    total_fp = len(effective_fffs) * max(len(products), 1)
    frames_done = 0
    total_tiles_saved = 0
    total_tiles_skipped = 0
    if _pt:
        _pt.update(map_type,
                   step="staging",
                   step_detail=f"Staging: 0/{len(effective_fffs)} frames…",
                   frames_total=total_fp,
                   frames_done=0, tiles_saved=0, tiles_skipped=0)

    run_start = time.perf_counter()
    # Submitting to the new orchestrator
    from .pipeline_orchestrator import get_orchestrator
    orchestrator = get_orchestrator()
    
    def submit_and_wait():
        orchestrator.submit_run(map_type, run_id, effective_fffs)
        
        # Poll DB for completion
        from ..core.db import get_pipeline_jobs_by_run, check_cancel_requested, JobCancelledError
        
        frames_done = 0
        total_tiles_saved = 0
        total_tiles_skipped = 0
        total_errors = 0
        
        while True:
            time.sleep(1.0)
            if check_cancel_requested(map_type):
                raise JobCancelledError("Job cancelled by user.")
                
            jobs = get_pipeline_jobs_by_run(map_type, run_id)
            if not jobs:
                continue
                
            done_count = 0
            err_count = 0
            
            for j in jobs:
                if j['state'] in ("READY", "SKIPPED", "ERROR", "CANCELLED"):
                    done_count += 1
                if j['state'] == "ERROR":
                    err_count += 1
                    total_errors += 1
                    
            frames_done = done_count
            
            if _pt:
                _pt.update(
                    map_type,
                    frames_done=frames_done,
                    step_detail=f"Pipeline Processing: {frames_done}/{len(jobs)} jobs done…",
                )
                
            if done_count == len(jobs):
                if err_count > 0:
                    raise RuntimeError(f"Found {err_count} pipeline errors for {map_type}/{run_id}.")
                break
                
        # Wait for publish worker to clear active_runs
        while f"{map_type}_{run_id}" in orchestrator.active_runs:
            time.sleep(0.5)

    try:
        submit_and_wait()
    except Exception as e:
        log.error(f"Pipeline error: {e}")
        if _pt:
            _pt.update(map_type, step="error", step_detail=str(e))
        raise

    log.info("Pipeline run complete: %s/%s now live", map_type, run_id)
    run_elapsed = time.perf_counter() - run_start
    if _pt:
        _pt.update(map_type, tile_duration_s=round(run_elapsed, 1))
    return {"map_type": map_type, "run_id": run_id, "duration_s": round(run_elapsed, 3)}
